import { getAds } from '../api';
import { PRODUCT_CATEGORIES, SERVICE_CATEGORIES, categoryInfo } from '../categories';
import { escapeHtml } from '../main';
import { card } from './home';

const tiles = (items: typeof PRODUCT_CATEGORIES, path: string) => `<div class="category-grid">${items.map((item) => `<a class="category-tile" href="#/catalog/${path}${item.slug}"><span>${item.icon}</span><strong>${item.name}</strong></a>`).join('')}</div>`;
const tabs = (active: string) => `<div class="catalog-tabs"><a class="${active === 'product' ? 'active' : ''}" href="#/catalog">🛍 Товары</a><a class="${active === 'service' ? 'active' : ''}" href="#/catalog/services">🛠 Услуги</a><a class="${active === 'all' ? 'active' : ''}" href="#/catalog?q=">Все</a></div>`;
export async function renderCatalog(params: Record<string, string> = {}) { const type = params.type || 'product'; const category = params.category || ''; const q = params.q || ''; try { const ads = await getAds({ type: type === 'all' ? undefined : type as 'product' | 'service', category: category || undefined, q: q || undefined }); if (!category && !q) return `<section class="page-heading"><span class="eyebrow">Маркетплейс</span><h1>${type === 'service' ? 'Услуги' : 'Товары'}</h1><p>Выберите категорию, чтобы начать поиск.</p></section>${tabs(type)}${tiles(type === 'service' ? SERVICE_CATEGORIES : PRODUCT_CATEGORIES, type === 'service' ? 'services/' : 'category/')}<section class="section catalog-all"><a class="text-link" href="#/catalog?q=&type=${type}">${type === 'service' ? 'Все услуги' : 'Все товары'} →</a></section>`; return `<section class="page-heading"><span class="eyebrow">${type === 'service' ? 'Услуги' : type === 'all' ? 'Все объявления' : 'Товары'}</span><h1>${category ? `${categoryInfo(type, category).icon} ${categoryInfo(type, category).name}` : 'Результаты поиска'}</h1></section>${tabs(type)}<form class="filters" id="catalog-filters"><input name="q" value="${escapeHtml(q)}" placeholder="Поиск"><input type="hidden" name="type" value="${type}"><button class="button primary">Найти</button></form><div class="results-meta">Найдено: ${ads.length}</div><div class="ad-grid">${ads.length ? ads.map(card).join('') : '<div class="empty">Ничего не найдено</div>'}</div>`; } catch (error) { return `<div class="error">${escapeHtml((error as Error).message)}</div>`; } }
export function bindCatalog() { document.querySelector<HTMLFormElement>('#catalog-filters')?.addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.currentTarget as HTMLFormElement); const type = String(data.get('type') || 'all'); location.hash = `#/catalog?q=${encodeURIComponent(String(data.get('q') || ''))}&type=${type}`; }); }
